# Modified by engelsofta in 2026 for Engelsoft BACstac; derived from the Bepacom BACnet/IP add-on.
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Engelsoft BACstac
version: "1.3.1"
slug: engelsoft_bacstac
description: Engelsoft BACstac makes BACnet/IP devices available to Home Assistant through an API.
url: "https://github.com/engelsofta/engelsoft-bacstac-ha-addon"
image: "ghcr.io/engelsofta/engelsoft-bacstac"
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_entry: webapp
host_network: true
hassio_api: true
panel_icon: mdi:router-wireless-settings
panel_title: Engelsoft BACstac
ports:
  47808/udp: 47808
ports_description:
  47808/udp: BACnet port
options:
  objectName: Engelsoft BACstac
  address: auto
  objectIdentifier: 420
  loglevel: WARNING
  segmentation: segmentedBoth
  api_token: ""
schema:
  objectName: str
  address: str
  objectIdentifier: int
  foreignBBMD: str?
  foreignTTL: int(1,65535)?
  vendorIdentifier: int?
  maxApduLengthAccepted: int?
  segmentation: list(segmentedBoth|segmentedTransmit|segmentedReceive|noSegmentation)?
  maxSegmentsAccepted: int?
  loglevel: list(DEBUG|INFO|WARNING|ERROR|CRITICAL|)
  api_token: password?
